[package]
name = "satellite"
version = "0.1.0"
authors = ["Rich Infante <rich@richinfante.com>"]
license = "MIT"
repository = "https://github.com/richinfante/satellite-rs"
readme = "README.md"
edition = "2018"

[dependencies]
chrono = { version = "0.4" }
thiserror = "1.0.29"
